PROGRAM := $(shell basename $$(dirname $$(pwd)))


all: build

debug:
	make build CXXFLAGS="-g"

build : 
	mkdir -p build
	g++ main.cpp $(CXXFLAGS) -o build/$(PROGRAM)

build/$(PROGRAM): main.cpp
	mkdir -p build
	g++ main.cpp -o build/${PROGRAM}

clean:
	rm -rf build

.PHONY: build
